[package]
name = "rweb-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.58"
fastrand = "1.7.0"
rweb = "0.15"
serde = "1.0.137"
thiserror = "1.0.31"
tokio = "1"
